### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by rsignavong** [meilisearch/MeiliES#49]
Hello,

I was looking for an EventStore and reach this wonderful project from Meilisearch.

But looking at the last commit date and activities I was wondering if the project is still active.

Can you tell me if this project continues to develop?

**Comment by qdequele** [comment]
Hello @rsignavong, we don't maintain anymore this repository. We continue to use it for a specific application, but it will probably be changed to another solution in a few times.
